name: vlb
channels:
- anaconda
- conda-forge
- menpo
- defaults
dependencies:
- freetype
- libgcc
- libgfortran
- bzip2
- ca-certificates
- dbus
- expat
- gettext
- gst-plugins-base
- gstreamer
- jasper
- jpeg
- libffi
- libpng
- libtiff
- libxcb
- ncurses
- openblas
- openssl
- pcre
- pytz
- readline
- sqlite
- tqdm
- xorg-libxau
- xorg-libxdmcp
- xz
- zlib
- asn1crypto
- backports_abc
- blas
- certifi
- cffi
- chardet
- cryptography
- cryptography-vectors
- cycler
- cython
- decorator
- fontconfig
- glib
- hdf5
- icu
- idna
- intel-openmp
- ipython_genutils
- jsonschema
- jupyter_core
- libgfortran-ng
- libiconv
- libxml2
- matplotlib
- mkl
- nbformat
- numpy
- olefile
- opencv
- pillow
- pip
- plotly
- pycparser
- pyopenssl
- pyparsing
- pyqt
- pysocks
- python
- qt
- requests
- retrying
- scikit-learn
- scipy
- setuptools
- sip
- six
- tk
- tornado
- traitlets
- urllib3
- wheel
- cyvlfeat
- pytorch
